stages:
  - test

.base:
  image: ruby:2.7.5
  cache:
    key: rat-app-name
    paths:
      - apt-cache/
      - vendor/ruby
      - node_modules/
    policy: pull
  before_script:
    - apt update -qq && apt -o dir::cache::archives="$APT_CACHE_DIR" install -yqq nodejs default-libmysqlclient-dev default-mysql-client
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor

.base_db:
  image: public.ecr.aws/sample/gitlab-ci-ruby-chrome:2.7.5
  services:
    - postgres:latest
  cache:
    key: gems_and_packages
    paths:
      - apt-cache/
      - vendor/ruby
    policy: pull
  variables:
    GITLAB_CI_FFI: ffi_for_ci
    DB_HOST: postgres
    POSTGRES_DB: sample
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: sample
    RAILS_ENV: test
    DISABLE_SPRING: 1
    BUNDLE_PATH: vendor/bundle
  before_script:
    - rm /etc/localtime && ln -s /usr/share/zoneinfo/Asia/Taipei /etc/localtime
    - cp config/config.yml.ref config/config.yml
    - cp config/database.yml.ci config/database.yml
    - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
    - apt update -qq && apt -o dir::cache::archives="$APT_CACHE_DIR" install -yqq default-libmysqlclient-dev default-mysql-client libvips
    - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor
    - bundle exec rake db:create db:migrate

rspec:
  extends: .base_db
  stage: test
  script:
    - bundle exec rspec spec/

rubocop:
  extends: .base
  stage: test
  cache:
    policy: pull
  script:
    - bundle exec rubocop --config .rubocop.yml

bundle_audit:
  extends: .base
  stage: test
  cache:
    policy: pull
  script:
    - bundle exec bundle audit check --update

brakeman:
  extends: .base
  stage: test
  cache:
    policy: pull-push
  artifacts:
    name: brakeman_report
    when: always
    paths:
      - brakeman/
  script:
    - bundle exec brakeman -q --no-exit-on-warn --no-exit-on-error -o reports/depscan.json -c .brakeman.yml
  artifacts:
    when: always
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - $CI_PROJECT_DIR/reports/
